include ':app'
rootProject.name = "schoolquiz"
include ':settings'
include ':common'
include ':shop'
include ':userguide'
include ':network'
include ':core'
include ':log-api'
include ':logger-compiler-plugin'
include ':logger-processor'
include ':test-app'
include ':logger-gradle-plugin'
// Используем logger-gradle-plugin как внешнюю зависимость из локального Maven репозитория
