package com.tpov.schoolquiz.presentation.core

const val PATH_LIST_PLAYERS = "players/listPlayers"
const val PATH_LIST_READ = "players/read"
const val PATH_PLAYERS = "players"
const val PATH_CHAT = "chat"
const val PATH_PHOTO = "picture"
const val PATH_PROFILES = "Profiles"
const val PATH_TRANSLATE = "PersonalMassage/translate"
const val PATH_LIST_TPOV_ID = "listTpovId"
const val PATH_PLAYERS_QUIZ = "players/quiz"
const val PATH_ID_QUIZ = "players/idQuiz"

const val KEY_VERSION_QUIZ = "versionQuiz"
const val KEY_ID_USER = "idUser"
const val KEY_QUALIFICATION = "qualification"
const val KEY_ADMIN = "admin"
const val KEY_SPONSOR = "sponsor"
const val KEY_TESTER = "tester"
const val KEY_STARS_ALL_PLAYER = "starsAllPlayer"
const val KEY_STARS_PLAYER = "starsPlayer"
const val KEY_RATING = "rating"
const val KEY_STARS = "stars"
const val KEY_STARS_ALL = "starsAll"

const val KEY_ADD_POINTS = "addPoints"
const val KEY_ADD_TROPHY = "addTrophy"
const val KEY_ADD_MASSAGE = "addMassage"
const val KEY_ADD_NOLICS = "addNolics"
const val KEY_ADD_GOLD = "addGold"
const val KEY_ADD_SKILL = "addSkill"

const val PATH_QUIZ = "quiz"
const val PATH_QUESTION = "question"
const val PATH_QUESTION_DETAIL = "question_detail"

const val PATH_HOME_QUIZ = "quiz8"
const val PATH_TOURNIRE_LEADER_QUIZ = "quiz7"
const val PATH_TOURNIRE_QUIZ = "quiz6"
const val PATH_ARENA_QUIZ = "quiz5"
const val PATH_ADMIN_QUIZ = "quiz4"
const val PATH_MODERATOR_QUIZ = "quiz3"
const val PATH_TESTER_QUIZ = "quiz2"
const val PATH_USER_QUIZ = "quiz1"

const val PATH_HOME_QUESTION = "question8"
const val PATH_TOURNIRE_LEADER_QUESTION = "question7"
const val PATH_TOURNIRE_QUESTION = "question6"
const val PATH_ARENA_QUESTION = "question5"
const val PATH_ADMIN_QUESTION = "question4"
const val PATH_MODERATOR_QUESTION = "question3"
const val PATH_TESTER_QUESTION = "question2"
const val PATH_USER_QUESTION = "question1"

const val PATH_HOME_QUESTION_DETAIL = "question_detail8"
const val PATH_TOURNIRE_LEADER_QUESTION_DETAIL = "question_detail7"
const val PATH_TOURNIRE_QUESTION_DETAIL = "question_detail6"
const val PATH_ARENA_QUESTION_DETAIL = "question_detail5"
const val PATH_ADMIN_QUESTION_DETAIL = "question_detail4"
const val PATH_MODERATOR_QUESTION_DETAIL = "question_detail3"
const val PATH_TESTER_QUESTION_DETAIL = "question_detail2"
const val PATH_USER_QUESTION_DETAIL = "question_detail1"