package com.tpov.schoolquiz.presentation.create

import android.graphics.drawable.BitmapDrawable
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.tpov.common.domain.entity.QuestionEntity
import com.tpov.common.domain.entity.QuizEntity
import com.tpov.common.domain.entity.QuizPathWithQuizEntity
import com.tpov.common.domain.entity.QuizPathWithQuizEntity.Companion.TYPE_USER_CREATE
import com.tpov.common.domain.usecase.InsertQuizUseCase
import com.tpov.schoolquiz.presentation.create.model.QuestionItem
import kotlinx.coroutines.launch
import javax.inject.Inject

class SimpleCreateQuizViewModel @Inject constructor(
    private val insertQuizUseCase: InsertQuizUseCase
    // Add other use cases if needed
) : ViewModel() {

    private val _questions = MutableLiveData<List<QuestionItem>>(emptyList())
    val questions: LiveData<List<QuestionItem>> = _questions

    private val _showQuizDetailsDialog = MutableLiveData<Boolean>()
    val showQuizDetailsDialog: LiveData<Boolean> = _showQuizDetailsDialog

    init {
        // Initialize with one empty question
        addQuestion()
    }

    fun addQuestion() {
        val currentList = _questions.value ?: emptyList()
        val newQuestionNumber = currentList.size + 1
        val newQuestion = QuestionItem(
            id = newQuestionNumber, // Temporary ID, will be replaced by DB ID
            questionText = "",
            answers = mutableListOf( // Start with a few empty answers
                QuestionItem.AnswerItem("", false),
                QuestionItem.AnswerItem("", false)
            ),
            image = null,
            typeQuestion = 0 // Default type
        )
        _questions.value = currentList + newQuestion
    }

    fun updateQuestion(updatedQuestion: QuestionItem) {
        val currentList = _questions.value?.toMutableList() ?: return
        val index = currentList.indexOfFirst { it.id == updatedQuestion.id }
        if (index != -1) {
            currentList[index] = updatedQuestion
            _questions.value = currentList
        }
    }

    fun triggerQuizDetailsDialog() {
        _showQuizDetailsDialog.value = true
    }

    fun resetQuizDetailsDialogTrigger() {
        _showQuizDetailsDialog.value = false
    }

    fun saveQuiz(name: String, image: BitmapDrawable?, questionsList: List<QuestionItem>) {
        viewModelScope.launch {
            val quizEntity = QuizEntity(
                id = 0, // Auto-generated by Room
                name = name,
                version = 1,
                type = TYPE_USER_CREATE, // Or some other appropriate type
                countPoints = questionsList.sumOf { it.points }, // Calculate points based on questions
                date = System.currentTimeMillis(),
                image = image,
                hardQuestion = questionsList.any { it.isHard },
                idQuiz = 0, // This might need clarification, seems redundant with id
                translater = "", // Not used in simple mode
                update = false,
                item = 0, // This might need clarification
                language = "" // Not used in simple mode
            )

            val questionEntities = questionsList.map { questionItem ->
                QuestionEntity(
                    id = 0, // Auto-generated
                    nameQuestion = questionItem.questionText,
                    answer = questionItem.answers.firstOrNull { it.isCorrect }?.text ?: "",
                    typeQuestion = questionItem.typeQuestion,
                    image = questionItem.image,
                    points = questionItem.points,
                    hardQuestion = questionItem.isHard,
                    idQuiz = 0, // Will be set after quiz is inserted
                    numQuestion = questionItem.id, // Or maintain order
                    codeAnswer = questionItem.answers.joinToString(";") { it.text },
                    codeCorrectAnswer = questionItem.answers.indexOfFirst { it.isCorrect }.toString(),
                    translater = "", // Not used
                    date = System.currentTimeMillis(), // Not used
                    language = "", // Not used
                    logo = null // Not used
                )
            }

            val quizPath = QuizPathWithQuizEntity(
                id = 0, // Auto-generated
                path = "", // Determine path if needed, or leave empty
                nameQuiz = name,
                type = TYPE_USER_CREATE,
                data = System.currentTimeMillis(),
                countPoints = quizEntity.countPoints,
                stars = 0, // Default stars
                countTry = 0, // Default tries
                idQuiz = 0, // Will be set after quiz is inserted
                quizEntity = quizEntity,
                questionEntity = questionEntities,
                image = image?.bitmap?.toString() // Or handle image path
            )

            // TODO: This use case might need adjustment if it expects a different structure
            // or if questions need to be inserted separately and linked to the quiz.
            // insertQuizUseCase(quizPath)
        }
    }
}

// Data class to represent a question in the UI for SimpleCreateQuizActivity
data class QuestionItem(
    val id: Int, // Can be a temporary ID for UI purposes before DB insertion
    var questionText: String,
    var answers: MutableList<AnswerItem>,
    var image: BitmapDrawable?,
    var typeQuestion: Int = 0, // 0 for single choice, 1 for multiple choice, etc.
    var points: Int = 1, // Default points
    var isHard: Boolean = false
) {
    data class AnswerItem(
        var text: String,
        var isCorrect: Boolean
    )
}
