plugins {
    id("schoolquiz.android.library")
}

android {
    namespace = "com.tpov.schoolquiz.platform.firebase"
}

dependencies {
    implementation(project(":shared:core:stats"))
    implementation(project(":shared:core:sync"))
    implementation(project(":shared:core:network"))
    implementation(project(":shared:core:outbox"))
    implementation(project(":shared:core:question-schema"))
    implementation(project(":shared:core:catalog:domain"))
    implementation(project(":shared:core:catalog:data"))
    implementation(project(":shared:feature:quest:data"))
    implementation(project(":shared:feature:quest-authoring:data"))
    implementation(project(":shared:feature:internet:profile:data"))
    implementation(project(":shared:feature:internet:profile:domain"))
    implementation(project(":shared:feature:internet:leaderboard:data"))
    implementation(project(":shared:feature:internet:leaderboard:domain"))
    implementation(project(":shared:feature:economy:data"))
    implementation(project(":shared:feature:economy:domain"))
    implementation(project(":shared:feature:section:data"))
    implementation(project(":shared:feature:theme:data"))
    implementation(project(":shared:feature:lesson:data"))
    implementation(project(":shared:feature:lesson:domain"))
    implementation(project(":shared:feature:lesson-runner:data"))
    implementation(project(":shared:feature:lesson-runner:domain"))
    implementation(project(":shared:core:leaderboard"))
    implementation(project(":shared:feature:question:data"))
    implementation(project(":shared:core:analytics"))
    implementation(libs.koin.core)
    implementation(libs.koin.android)
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.analytics)
    implementation(libs.firebase.crashlytics)
    implementation(libs.firebase.firestore)
    implementation(libs.firebase.auth.ktx)
    implementation(libs.firebase.database.ktx)
    implementation(libs.firebase.storage.ktx)
    implementation(libs.firebase.functions)
    implementation(libs.firebase.appcheck.play.integrity)
    debugImplementation(libs.firebase.appcheck.debug)
    implementation(libs.androidx.credentials)
    implementation(libs.androidx.credentials.play.services)
    implementation(libs.googleid)
    implementation(libs.play.services.base)
    implementation(libs.play.services.basement)
    testImplementation(libs.junit4)
    testImplementation(libs.mockk)
    testImplementation(libs.kotlinx.coroutines.test)
}
